apiVersion: build.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: buildah
spec:
  parameters:
  - name: BUILDER_IMAGE
    description: The location of the buildah builder image.
  - name: IMAGE
    description: The name of the image to push.
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile

  steps:
  - name: build
    image: ${BUILDER_IMAGE}
    args: ['bud', '-f', '${DOCKERFILE}', '-t', 'image', '.']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers

  - name: push
    image: ${BUILDER_IMAGE}
    args: ['push', 'image', 'docker://${IMAGE}']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers

  volumes:
  - name: varlibcontainers
    emptyDir: {}
